# -*- coding: utf-8 -*-
"""csv_heatmap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17GiOjb9ei8nULcs6d8l4W8kmlQIUApw6

<h1 align=center><b>Collapsed Building Heatmap with Folium</b></font></h1>

<br>

<p align="center">
    <img src="https://drive.google.com/uc?id=1dx98iliCTjuonFHX_orRz20O8S7CeTnW" height=300 width=2000 alt="GitHub">
</p>

<small>Picture Source: <a href="https://github.com/doguilmak">Doğu İlmak</a></small>

<br>

Folium is a Python library that makes it easy to create interactive maps and visualizations on web browsers. It's built on top of Leaflet, which is a popular JavaScript library for interactive maps. Folium allows you to generate maps with various features, including markers, popups, choropleths, and heatmaps, which can be displayed in an interactive HTML format.

<br>

Here's a brief overview of Folium's key features and concepts:

1.  **Map Creation**: Folium provides a simple way to create maps by specifying the center's latitude and longitude and an initial zoom level. You can create a basic map with just a single line of code.
    
2.  **Markers and Popups**: You can add markers to the map to indicate specific points of interest. Each marker can have a popup that displays additional information when clicked.
    
3.  **Choropleths**: Folium supports choropleth maps, where you can color areas (such as countries or regions) based on a numerical value. This is useful for visualizing data that varies geographically.
    
4.  **Heatmaps**: Heatmaps are a great way to visualize the density or intensity of data points on a map. Folium's `HeatMap` plugin allows you to create heatmaps from a list of coordinates.
    
5.  **Layer Control**: You can add multiple layers to a map and provide a control to toggle between them. This is particularly useful when you want to display different data sets or overlays on the same map.
    
6.  **Plugins and Extensions**: Folium has a variety of plugins and extensions that allow you to extend its functionality. These include plugins for clustering markers, drawing shapes, and more.
    
7.  **Export to HTML**: Once you've created your map with Folium, you can save it as an interactive HTML file. This HTML file can be opened in a web browser to interact with the map.
    
8.  **Integration with Pandas**: Folium seamlessly integrates with Pandas DataFrames, making it easy to visualize data directly from your data structures.

<br>

Folium is particularly useful when you want to share interactive maps with others without requiring them to install specialized software. It's widely used for visualizing geospatial data, creating interactive dashboards, and presenting insights in a visually engaging manner.

Keep in mind that Folium is just one of several tools available for geospatial visualization in Python. Depending on your needs and the complexity of your analysis, you might also explore other libraries like geopandas for more advanced geospatial capabilities.
"""

import folium
from folium.plugins import HeatMap
import pandas as pd

data = pd.read_csv('/content/collapsed_data.csv')

data.head()

center_lat = data['Latitude'].mean()
center_lon = data['Longitude'].mean()
m = folium.Map(location=[center_lat, center_lon], zoom_start=10)

heat_data = [[row['Latitude'], row['Longitude']] for index, row in data.iterrows()]

HeatMap(heat_data, radius=15).add_to(m)
m.save('heatmap.html')

from google.colab import files
files.download('/content/heatmap.html')

"""# Contact Me
<p>If you have something to say to me please contact me:</p>

<ul>
  <li>Twitter: <a href="https://twitter.com/Doguilmak">Doguilmak</a></li>
  <li>Mail address: doguilmak@gmail.com</li>
</ul>
"""

from datetime import datetime
print(f"Changes have been made to the project on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")